apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: composer-ai-config
  namespace: openshift-gitops
  labels:
    gitops.ownedBy: cluster-config
    tenant: composer-ai
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: appOfApps
    repoURL: 'https://github.com/nstrug/appOfApps.git'
    targetRevision: HEAD
    helm:
      parameters:
        - name: application.defaultNamespace
          value: composer-ai-app
        - name: clusterDomain
          value: apps.cluster-hm6h6.hm6h6.sandbox2635.opentlc.com
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false